/* DO NOT EDIT THIS FILE - it is machine generated */
#include "global.h"
/* Header for class moe_ore_silk_SilkCodec */

#ifndef _Included_moe_ore_silk_SilkCodec
#define _Included_moe_ore_silk_SilkCodec
#ifdef __cplusplus
extern "C" {
#endif
#undef moe_ore_silk_SilkCodec_DEFAULT_RATE
#define moe_ore_silk_SilkCodec_DEFAULT_RATE 24000L
/*
 * Class:     moe_ore_silk_SilkCodec
 * Method:    nativeEncodeSilk
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_moe_ore_silk_SilkCodec_nativeEncodeSilk
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     moe_ore_silk_SilkCodec
 * Method:    nativeDecodeSilk
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_moe_ore_silk_SilkCodec_nativeDecodeSilk
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
