/* DO NOT EDIT THIS FILE - it is machine generated */
#include "global.h"
/* Header for class moe_ore_silk_LameCoder */

#ifndef _Included_moe_ore_silk_LameCoder
#define _Included_moe_ore_silk_LameCoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    initializeDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_ore_silk_LameCoder_initializeDefault
  (JNIEnv *, jclass);

/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    initialize
 * Signature: (IIIIFIIIIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_moe_ore_silk_LameCoder_initialize
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jint, jint, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    lameClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_ore_silk_LameCoder_lameClose
  (JNIEnv *, jclass);

/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_moe_ore_silk_LameCoder_encodeFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    initDecoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_ore_silk_LameCoder_initDecoder
  (JNIEnv *, jclass);

/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    closeDecoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moe_ore_silk_LameCoder_closeDecoder
  (JNIEnv *, jclass);

/*
 * Class:     moe_ore_silk_LameCoder
 * Method:    decodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_moe_ore_silk_LameCoder_decodeFile
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
