/* DO NOT EDIT THIS FILE - it is machine generated */
#include "global.h"
/* Header for class moe_ore_silk_AudioUtils
#include "libavformat/avformat.h"
#include "libavcodec/avcodec.h" */

#ifndef _Included_moe_ore_silk_AudioUtils
#define _Included_moe_ore_silk_AudioUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_ore_silk_AudioUtils
 * Method:    check
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moe_ore_silk_AudioUtils_check
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
